# Table formatting All Deployments

## STOP

This script formats the summarized data for all deployments in the Community HEPA paper. **Have you run `Community_All_modpm_stats.Rmd` ?**

## Set up
Load libraries, define file paths, include participant IDs to be processed
```{r}
# Import relevant libraries
library(tidyverse)
```

Set working directory
NOTE: The working directory is dependent by user. 
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/hepa-summer23")
```

```{r}
# Get file path
if (!endsWith(getwd(), "hepa-summer23")) {
  stop("Incorrect working directory")
}
```

```{r}
# Set path to data
path_to_data <- "summary/Community_All/"
```

## Load Data
```{r}
filepath <- paste0(path_to_data, "s_All_M_quants.csv")
summary_all <- read_csv(filepath, show_col_types = FALSE) %>% select(-c(1))

# Mapping
id_to_name <- c("CM" = "Cardinal Medeiros (Roxbury)", "RI" = "Independent Homes (Roxbury)", "IB" = "Indigo Block (Roxbury)", "CH" = "Revere City Hall", "RH" = "Revere High School", "MF" = "Mothers Out Front (East Boston)", "LF" = "Little Folks (East Boston)","SS" = "Shining Star (East Boston)")
```
## Modify Data
```{r}
# For indoor data
summary_all %>%
  filter(environment == "indoor", case == "redu") %>%
  arrange(area, place_id, room_type) %>%
  mutate(place_names = id_to_name[place_id], 
         id = group_indices(., participant_id, place_id)) %>%
  select(id, place_names, room_type, participant_id, type, mean, median, q5, q25, q75, q95) %>%
  mutate(across(mean:q95, \(x) round(x, 1))) %>%
  write.csv("artifacts/Community_All/indoor_reduction.csv", row.names = FALSE)
```
```{r}
# For ratio data
summary_all %>%
  filter(environment == "ratio", case == "redu") %>%
  arrange(area, place_id, room_type) %>%
  mutate(place_names = id_to_name[place_id], 
         id = group_indices(., participant_id, place_id)) %>%
  select(id, place_names, room_type, participant_id, type, mean, median, q5, q25, q75, q95) %>%
  mutate(across(mean:q95, \(x) round(x, 1))) %>%
  write.csv("artifacts/Community_All/io-ratio_reduction.csv", row.names = FALSE)
```
```{r}
# For indoor data
summary_all %>%
  filter(environment == "indoor", case == "redu", participant_id != "all",
         type == "pm25") %>%
  count(room_type)
```

```{r}
# For indoor data
summary_all %>%
  filter(environment == "indoor", case == "redu", participant_id != "all",
         type == "pm25") %>%
  mutate(place_names = id_to_name[place_id]) %>%
  count(room_type, place_names)
```

```{r}
summary_all %>% 
  filter(participant_id == "all", type == "pm1") %>%
  pivot_wider(id_cols = c(room_type), names_from = c(case, environment), 
              values_from = mean) %>%
  select(order(colnames(.))) %>%
  select(room_type, everything()) %>% select(-redu_outdoor) %>%
  mutate(across(where(is.numeric), signif, 3)) %>%
  mutate(across(contains("redu"), ~paste0(.x, "%"))) -> mean_table
```

```{r}
write_csv(mean_table, "artifacts/Community_All/mean_stats.csv")
```

```{r}
summary_all %>%
  filter(participant_id == "all", type == "pm1") %>%
  select(room_type, environment, case, mean, median, q25, q95) %>%
  pivot_wider(names_from = case, values_from = mean:q95) %>%
  arrange(environment) %>%
  mutate(across(where(is.numeric), \(x) signif(x, digits = 3))) -> percentile_table
```

```{r}
custom_order <- function(names) {
  split_names <- strsplit(names, "_")
  order <- order(sapply(split_names, `[`, 2), sapply(split_names, `[`, 1))
  names[order]
}
```

```{r}
percentile_table <- percentile_table %>%
  select(custom_order(names(percentile_table)))

```

```{r}
write_csv(percentile_table, "artifacts/Community_All/percentile_stats.csv")
```

