```{r}
library(data.table)
library(tidyverse)
```


## Script for pre-processing CPC data from text files
```{r}
# Get file path
if (!endsWith(getwd(), "hepa-summer23")) {
  stop("Incorrect working directory")
}

# # If file path doesn't end with the root folder "hepa-summer23", set to that folder on your PC
# setwd(dir)
```

```{r}
# Set path to data
path_to_data <- "data/HAFTRAP/OH/cpc/"

# Set data category
data_cat <- "OH_C"
```

```{r}
# List all directories in raw data
folders <- list.dirs(path = paste0(path_to_data, "very_raw_data/"), full.names = TRUE, recursive = TRUE)
```

```{r}
# Loop through each subfolder
for (subfolder in folders) {
  
  # Split path into individual parts
  path_parts <- strsplit(subfolder, split = "/")
  
  # Only evaluate directories that have a depth of 7 from the root (a.k.a with 
  # data files)
  if (length(path_parts[[1]]) == 7) {
    
    # Isolate environment and participant ID
    env <- path_parts[[1]][6]
    id <- path_parts[[1]][7]
  
    # Skip unwanted files
    if (id == "Pre data" || grepl("bad", id)) {
      print(paste("Skipped", env, "data for participant", id))
      next
    }
    
    print(paste("Reading", env, "data for participant", id, "..."))
    
    # Try catch statement to handle errors 
    # (Warning: this is a janky fix because I don't really understand why this 
    # error was happening in the first place)
    main_df <- tryCatch({
      # Get list of files in directory
      list.files(path = subfolder, full.names = TRUE) %>% 
        # Read into dataframe (datetime variables, concent, inlttmp)
        map_df(~fread(.x, header = TRUE, skip = 13, select = c(1, 2, 4, 11)) %>%
        # Convert all concentration values to double
        # Note: pipe is inside map_df - the conversion happens for every file 
        # read into dataframe
        mutate(concent = as.double(concent)))},
      
      # Errors here only happened for participant 45451, where mutate didn't work
      error = function(cond) {
        print("Error! Reading file alternatively")
        # Get list of files and read, except without making concentrations double
        # Note: data for 45451 is uniform so setting datatype isn't required
        # Yes this part doesn't make sense, is a patchy coincidental fix for a 
        # problem I don't really understand
        temp_df <- list.files(path = subfolder, full.names = TRUE) %>% 
          map_df(~fread(.x, header = TRUE, skip = 13, select = c(1, 2, 4, 11)))
        
        # Return this alternative dataframe instead
        return(temp_df)})
      
    # Make new file name
    new_file_name <- paste(data_cat, id, env, sep = "_")
    print(paste("Writing", new_file_name, "..."))
    
    # Write into appropriate path
    fwrite(main_df, paste0(path_to_data, new_file_name, ".csv"))
    print(paste("Downloaded", env, "data for participant ID", id))
  }
}
```

1) Difference between aveconc, concent, and rawconc?
2) Update data guide with CPC data pre-processing org, new script
3) Add more visualizations to guide
4) What is going on with 45451