# Data Extraction and Cleaning
```{r}
# Imports
library(tidyverse)
library(openair)
library(corrplot)
library(ggplot2)
library(ggpmisc)

```

```{r}
# Define indoor file to be imported, set time of HEPA purifier install
is_file <- 'data/HAFTRAP_sham_indoor.csv'
os_file <- 'data/HAFTRAP_sham_outdoor.csv'
ih_file <- 'data/HAFTRAP_hepa_indoor.csv'
oh_file <- 'data/HAFTRAP_hepa_outdoor.csv'
```

## Import and prepare data
```{r}
# Import indoor sham data
sham_indoor <- read.csv(is_file)

# Import outdoor sham data
sham_outdoor <- read.csv(os_file)

# Import indoor hepa data
hepa_indoor <- read.csv(ih_file)

# Import outdoor hepa data
hepa_outdoor <- read.csv(oh_file)

```

```{r}
# View dataframes
head(hepa_indoor, 5)
```


```{r}
# Reformat timestamps to time object

sham_indoor$date <- as.POSIXct(strptime(sham_indoor$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
sham_indoor$date_round <- round_date(sham_indoor$date, unit = "minute")

sham_outdoor$date <- as.POSIXct(strptime(sham_outdoor$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
sham_outdoor$date_round <- round_date(sham_outdoor$date, unit = "minute")

hepa_indoor$date <- as.POSIXct(strptime(hepa_indoor$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
hepa_indoor$date_round <- round_date(hepa_indoor$date, unit = "minute")

hepa_outdoor$date <- as.POSIXct(strptime(hepa_outdoor$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
hepa_outdoor$date_round <- round_date(hepa_outdoor$date, unit = "minute")
```

```{r}
head(hepa_indoor, 3)
```

```{r}
# # Remove duplicate rows based on date
# indoor_data <- distinct(indoor_data, indoor_data$date, .keep_all = TRUE)
# outdoor_data <- distinct(outdoor_data, outdoor_data$date, .keep_all = TRUE)

```

```{r}
# Append all variables with "outdoor_" or "indoor_" respectively
colnames(sham_indoor) <- paste0('indoor_', colnames(sham_indoor))
colnames(sham_outdoor) <- paste0('outdoor_', colnames(sham_outdoor))

colnames(hepa_indoor) <- paste0('indoor_', colnames(hepa_indoor))
colnames(hepa_outdoor) <- paste0('outdoor_', colnames(hepa_outdoor))
```

```{r, results = 'hide'}
# Time-sync indoor, outdoor data
# Join dataframes by syncing indoor_date and outdoor_date columns
sham_joined_data <- left_join(sham_indoor, sham_outdoor, by = c("indoor_date_round" = "outdoor_date_round"))

hepa_joined_data <- left_join(hepa_indoor, hepa_outdoor, by = c("indoor_date_round" = "outdoor_date_round"))

# Renaming synced date columns back to just 'date'
sham_joined_data$date <- sham_joined_data$indoor_date

hepa_joined_data$date <- hepa_joined_data$indoor_date

# Keeping distinct time-stamps
sham_joined_data %>% distinct(sham_joined_data$indoor_date, .keep_all = TRUE);

hepa_joined_data %>% distinct(hepa_joined_data$indoor_date, .keep_all = TRUE);

# # Attach for easier reference while graphing
# attach(joined_data)

```

```{r}
# #Initial time series
timePlot(sham_joined_data, pollutant = c('indoor_pm1', 'indoor_pm25', 'indoor_pm10'), main = "Indoor Sham Data", normalize = TRUE, name.pol = c("pm1", "pm25", "pm10"))

timePlot(sham_joined_data, pollutant = c('outdoor_pm1', 'outdoor_pm25', 'outdoor_pm10'), main = "Outdoor Sham Data", normalize = TRUE, name.pol = c("pm1", "pm25", "pm10"))

timePlot(hepa_joined_data, pollutant = c('indoor_pm1', 'indoor_pm25', 'indoor_pm10'), main = "Indoor HEPA Data", normalize = TRUE, name.pol = c("pm1", "pm25", "pm10"))

timePlot(hepa_joined_data, pollutant = c('outdoor_pm1', 'outdoor_pm25', 'outdoor_pm10'), main = "Outdoor HEPA Data", normalize = TRUE, name.pol = c("pm1", "pm25", "pm10"))
```


```{r}
# Indoor data timevariation
timeVariation(sham_joined_data, pollutant = c("indoor_pm1", "indoor_pm25", "indoor_pm10"))

timeVariation(hepa_joined_data, pollutant = c("indoor_pm1", "indoor_pm25", "indoor_pm10"))

# Outdoor data timevariation
timeVariation(sham_joined_data, pollutant = c("outdoor_pm1", "outdoor_pm25", "outdoor_pm10"))

timeVariation(hepa_joined_data, pollutant = c("outdoor_pm1", "outdoor_pm25", "outdoor_pm10"))
```


```{r}
sham_corr_data <- select(sham_joined_data, indoor_pm1, indoor_pm25, indoor_pm10, outdoor_pm1, outdoor_pm25, outdoor_pm10)
N <- cor(na.omit(sham_corr_data), use = "p")
corrplot(N, method = 'color', main = "Sham Correlation Plot")

hepa_corr_data <- select(hepa_joined_data, indoor_pm1, indoor_pm25, indoor_pm10, outdoor_pm1, outdoor_pm25, outdoor_pm10)
N <- cor(na.omit(hepa_corr_data), use = "p")
corrplot(N, method = 'color', main = "HEPA Correlation Plot")
```

```{r}
# Sham Indoor PM 1 vs. Indoor PM 2.5
ggplot(sham_joined_data, aes(x = indoor_pm1, y = indoor_pm25)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = expression("Sham Correlation Plot (Indoor PM"[1]*" vs. Indoor PM"[2.5]*")"), x = expression("Indoor PM"[1]), y = expression("Indoor PM"[2.5])) +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))

# Sham Outdoor PM 1 vs. Outdoor PM 2.5
ggplot(sham_joined_data, aes(x = outdoor_pm1, y = outdoor_pm25)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "Sham Correlation Plot (Outdoor PM1 vs. Outdoor PM2.5)", x = "Outdoor PM1", y = "Outdoor PM2.5") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))

# HEPA Indoor PM 1 vs. Indoor PM 2.5
ggplot(hepa_joined_data, aes(x = indoor_pm1, y = indoor_pm25)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "HEPA Correlation Plot (Indoor PM1 vs. Indoor PM2.5)", x = "Indoor PM1", y = "Indoor PM2.5") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))

# HEPA Indoor PM 2.5 vs. Indoor PM 10
ggplot(hepa_joined_data, aes(x = indoor_pm25, y = indoor_pm10)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "HEPA Correlation Plot (Indoor PM2.5 vs. Indoor PM10)", x = "Indoor PM2.5", y = "Indoor PM10") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))

# HEPA Outdoor PM 2.5 vs. Outdoor PM 10
ggplot(hepa_joined_data, aes(x = outdoor_pm25, y = outdoor_pm10)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "HEPA Correlation Plot (Outdoor PM2.5 vs. Outdoor PM10)", x = "Outdoor PM2.5", y = "Outdoor PM10") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))

# HEPA Indoor PM 2.5 vs. Outdoor PM 2.5
ggplot(hepa_joined_data, aes(x = indoor_pm25, y = outdoor_pm25)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "HEPA Correlation Plot (Indoor PM2.5 vs. Outdoor PM2.5)", x = "Indoor PM2.5", y = "Outdoor PM2.5") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))

# Sham Indoor PM 2.5 vs. Outdoor PM 2.5
ggplot(sham_joined_data, aes(x = indoor_pm25, y = outdoor_pm25)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "Sham Correlation Plot (Indoor PM2.5 vs. Outdoor PM2.5)", x = "Indoor PM2.5", y = "Outdoor PM2.5") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))


```
```{r}
# Sham Indoor PM 1 vs. Outdoor PM 1
ggplot(sham_joined_data, aes(x = indoor_pm1, y = outdoor_pm1)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "Sham Correlation Plot (Indoor PM1 vs. Outdoor PM1)", x = "Indoor PM10", y = "Outdoor PM1") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))
```

```{r}
# Hepa Indoor PM 1 vs. Outdoor PM 1
ggplot(hepa_joined_data, aes(x = indoor_pm1, y = outdoor_pm1)) +
  geom_point(alpha = 0.1) +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  labs(title = "Hepa Correlation Plot (Indoor PM1 vs. Outdoor PM1)", x = "Indoor PM1", y = "Outdoor PM1") +
  stat_poly_eq(formula = x ~ y,
               aes(label = paste(after_stat(eq.label), after_stat(rr.label), sep = "~~~")))
```

```{r}
si_mean <- mean(sham_indoor$indoor_pm25, na.rm = TRUE)
hi_mean <- mean(hepa_indoor$indoor_pm25, na.rm=TRUE)
so_mean <- mean(sham_outdoor$outdoor_pm25, na.rm = TRUE)
ho_mean <- mean(hepa_outdoor$outdoor_pm25, na.rm=TRUE)


```

```{r}
100*(si_mean - hi_mean)/si_mean
```
```{r}
100*(so_mean - ho_mean)/so_mean
```

```{r}
si_median <- median(sham_indoor$indoor_pm25, na.rm = TRUE)
hi_median <- median(hepa_indoor$indoor_pm25, na.rm=TRUE)
so_median <- median(sham_outdoor$outdoor_pm25, na.rm = TRUE)
ho_median <- median(hepa_outdoor$outdoor_pm25, na.rm=TRUE)
```

```{r}
100*(median(sham_indoor$indoor_pm25, na.rm = TRUE) - median(hepa_indoor$indoor_pm25, na.rm=TRUE))/median(sham_indoor$indoor_pm25, na.rm=TRUE)
```
```{r}
100*(median(sham_outdoor$outdoor_pm25, na.rm = TRUE) - median(hepa_outdoor$outdoor_pm25, na.rm=TRUE))/median(sham_outdoor$outdoor_pm25, na.rm=TRUE)
```
```{r}
100*((si_mean/so_mean) - (hi_mean/ho_mean))/(si_mean/so_mean)
```

```{r}
100*((si_median/so_median) - (hi_median/ho_median))/(si_median/so_median)
```
