```{r}
library(tidyverse)
```

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = "~/hepa-summer23")
```

```{r}
# # Get file path
# if (!endsWith(getwd(), "hepa-summer23")) {
#   stop("Incorrect working directory")
# }
```

```{r}
test_data <- summary_normal
```

## Plotting Function
```{r}
plot_heatmap <- function(joined_data, title) {
  # Sets order for displaying particles in heatmap
  particle_order <- c("PM 1", "PM 2.5", "PM 10")
  # Sets order for displaying summary stats in heatmap
  summary_order <- c("K Value", "Peak Width", "Peak Height")
  
  # Pre-process data before ploting
  joined_data %>%
    # Reshape for heatmap
    pivot_longer(mean:sd, names_to = "sum_type", values_to = "stat") %>%
    
    # Recode for accurate labels
    mutate(type = recode(type, "1" = "PM 1", "2.5" = "PM 2.5", 
                     "10" = "PM 10"),
         sum_type = recode(sum_type, "mean" = "Mean", "median" = "Median")) %>%
    
    # Arrange axes in specified order
    mutate(type = factor(type, levels = particle_order)) %>%
    mutate(sum_type = factor(sum_type, levels = summary_order)) %>%

    # Plot heatmap
    ggplot(aes(x = type, y = sum_type)) +
      # Fill with value of stat
      geom_tile(aes(fill = stat)) +
      # Print in value of stat
      geom_text(aes(label = paste0(round(stat, 1), "%"))) +
    
      # Set color scale
      scale_fill_gradient2(low = "#ff7f7f", high = "#DeF7E9", mid = "white") +
      # Set axis labels, title
      labs(title = title, x = "Particle Type", y = "Summary Statistic", 
           fill = "Reduction (%)") +
      # Set theme
      theme_minimal()
}
```

