```{r}
# Imports
library(tidyverse)
library(ggplot2)
library(data.table)
library(lubridate)
```

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = '/home/sjatti/Desktop/hepa-summer23')
```

Check for working directory
```{r}
# Check file path
if (!endsWith(getwd(), "hepa-summer23")) {
  stop("Incorrect working directory")
}
```

```{r}
# Vector of participant numbers' data to be processed
# Skipping 41211 for now because of funky data (look at CSVs)
participants <- c("41181", "41271", "42231", "42281", "42301", "42321",
                  "44241", "44621", "45361", "45411", "45451", "46591")
```

Paths
```{r}
# Set path to data
path_to_data <- "data/HAFTRAP/OH/modpm/"
```

## Load data
```{r}
# Load Mod-PM data from RData file
load(paste0(path_to_data, "cleaned_modpm.RData"))
```

# ```{r}
# # Define indoor file to be imported, set time of HEPA purifier install
# before_indoor_file <- "/home/sjatti/Desktop/hepa-summer23/data/CM_M_104_before_indoor.csv"
# after_indoor_file <- "/home/sjatti/Desktop/hepa-summer23/data/CM_M_104_after_indoor.csv"
# 
# before_outdoor_file <- "/home/sjatti/Desktop/hepa-summer23/data/CM_M_104_before_outdoor.csv"
# after_outdoor_file <- "/home/sjatti/Desktop/hepa-summer23/data/CM_M_104_after_outdoor.csv"
# ```
# 
# ## Import and prepare data
# ```{r}
# # Import indoor data
# before_indoor_data <- read.csv(before_indoor_file)
# after_indoor_data <- read.csv(after_indoor_file)
# 
# # Import outdoor data
# before_outdoor_data <- read.csv(before_outdoor_file)
# after_outdoor_data <- read.csv(after_outdoor_file)
# ```

```{r}
# before_indoor_data$date <- as.POSIXct(strptime(before_indoor_data$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
# before_indoor_data$date_round <- round_date(before_indoor_data$date, unit = "10 mins")
# 
# after_indoor_data$date <- as.POSIXct(strptime(after_indoor_data$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
# after_indoor_data$date_round <- round_date(after_indoor_data$date, unit = "10 mins")
# 
# before_outdoor_data$date <- as.POSIXct(strptime(before_outdoor_data$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
# before_outdoor_data$date_round <- round_date(before_outdoor_data$date, unit = "10 mins")
# 
# after_outdoor_data$date <- as.POSIXct(strptime(after_outdoor_data$timestamp_local, format = "%Y-%m-%dT%H:%M:%SZ", tz = "America/New_York"))
# after_outdoor_data$date_round <- round_date(after_outdoor_data$date, unit = "10 mins")

df <- main_df
df <- drop_na(df)
df$date_round <- round_date(df$date, unit = "10 mins")
      # filter(participant_id == person, case == c, 
      #        environment == env)
```

```{r}
# adds a boolean column depending on whether the day is a wknd or not
# before_indoor_data$is_wknd <- is.weekend(before_indoor_data$date)
# after_indoor_data$is_wknd <- is.weekend(after_indoor_data$date)
# 
# before_outdoor_data$is_wknd <- is.weekend(before_outdoor_data$date)
# after_outdoor_data$is_wknd <- is.weekend(after_outdoor_data$date)

# df$is_wknd_1 <- is.weekend(df$date)

df$wkdy <- wday(df$date)

df$is_wknd <- replace(df$wkdy, df$wkdy > 1 & df$wkdy < 7, "FALSE")
df$is_wknd <- replace(df$is_wknd, df$is_wknd == 1 | df$is_wknd == 7, "TRUE")
```

```{r}
# # isolate time
# before_indoor_data$time <- as.ITime(before_indoor_data$date_round)
# after_indoor_data$time <- as.ITime(after_indoor_data$date_round)
# 
# before_outdoor_data$time <- as.ITime(before_outdoor_data$date_round)
# after_outdoor_data$time <- as.ITime(after_outdoor_data$date_round)
# 
# # convert back to datetime object (will assign today's date to all)
# before_indoor_data$time <- as.POSIXct(before_indoor_data$time, format="%H:%M:%S")
# after_indoor_data$time <- as.POSIXct(after_indoor_data$time, format="%H:%M:%S")
# 
# before_outdoor_data$time <- as.POSIXct(before_outdoor_data$time, format="%H:%M:%S")
# after_outdoor_data$time <- as.POSIXct(after_outdoor_data$time, format="%H:%M:%S")

df$time <- as.ITime(df$date_round)
df$time <- as.POSIXct(df$time, format="%H:%M:%S")
```

```{r}
# Filtering for values above a certain threshold
# before_indoor_data <- subset(before_indoor_data, pm1 < 200 & pm25 < 250 & pm10 < 1000)
# after_indoor_data <- subset(after_indoor_data, pm1 < 200 & pm25 < 250 & pm10 < 1000)
# before_outdoor_data <- subset(before_outdoor_data, pm1 < 25 & pm25 < 50 & pm10 < 500)
# after_outdoor_data <- subset(after_outdoor_data, pm1 < 25 & pm25 < 50 & pm10 < 500)

# length(which(before_indoor_data$pm1 > 200))
# length(which(after_indoor_data$pm1 > 200))
# length(which(before_outdoor_data$pm1 > 25))
# length(which(after_outdoor_data$pm1 > 25))

# length(which(before_indoor_data$pm25 > 250))
# length(which(after_indoor_data$pm25 > 250))
# length(which(before_outdoor_data$pm25 > 50))
# length(which(after_outdoor_data$pm25 > 50))

# length(which(before_indoor_data$pm10 > 1000))
# length(which(after_indoor_data$pm10 > 1000))
# length(which(before_outdoor_data$pm10 > 500))
# length(which(after_outdoor_data$pm10 > 500))
```

```{r}
# create new dataframes with summary data to plot (mean/median)
# sum_before_indoor_data <- summary_dataframe(before_indoor_data)
# sum_after_indoor_data <- summary_dataframe(after_indoor_data)
# 
# sum_before_outdoor_data <- summary_dataframe(before_outdoor_data)
# sum_after_outdoor_data <- summary_dataframe(after_outdoor_data)

sum_df <- summary_dataframe(df)

# restructure dataframes for graphing
# graph_before_indoor_data <- pivot_longer(sum_before_indoor_data, mean_1:percent95_10, names_to = c(".value", "particle"), names_sep = "_")
# graph_after_indoor_data <- pivot_longer(sum_after_indoor_data, mean_1:percent95_10, names_to = c(".value", "particle"), names_sep = "_")
# 
# graph_before_outdoor_data <- pivot_longer(sum_before_outdoor_data, mean_1:percent95_10, names_to = c(".value", "particle"), names_sep = "_")
# graph_after_outdoor_data <- pivot_longer(sum_after_outdoor_data, mean_1:percent95_10, names_to = c(".value", "particle"), names_sep = "_")

graph_df <- pivot_longer(sum_df, mean_1:percent95_10, names_to = c(".value", "particle"), names_sep = "_")
```

```{r}
diurnal_plot(graph_df, "Before", "Indoor", "1")
diurnal_plot(graph_df, "Before", "Indoor", "2.5")
diurnal_plot(graph_df, "Before", "Indoor", "10")

diurnal_plot(graph_df, "After", "Indoor", "1")
diurnal_plot(graph_df, "After", "Indoor", "2.5")
diurnal_plot(graph_df, "After", "Indoor", "10")

diurnal_plot(graph_df, "Before", "Outdoor", "1")
diurnal_plot(graph_df, "Before", "Outdoor", "2.5")
diurnal_plot(graph_df, "Before", "Outdoor", "10")

diurnal_plot(graph_df, "After", "Outdoor", "1")
diurnal_plot(graph_df, "After", "Outdoor", "2.5")
diurnal_plot(graph_df, "After", "Outdoor", "10")
```

```{r}
# necessary functions

# function to create a new dataframe with summary data
summary_dataframe <- function(data) {
  data %>%
  group_by(is_wknd, time) %>%
  summarise(mean_1 = mean(pm1, na.rm = TRUE), mean_2.5 = mean(pm25), mean_10 = mean(pm10), median_1 = median(pm1), median_2.5 = median(pm25), median_10 = median(pm10), percent5_1 = quantile(pm1, 0.05), percent25_1 = quantile(pm1, 0.25), percent75_1 = quantile(pm1, 0.75), percent95_1 = quantile(pm1, 0.95), percent5_2.5 = quantile(pm25, 0.05), percent25_2.5 = quantile(pm25, 0.25), percent75_2.5 = quantile(pm25, 0.75), percent95_2.5 = quantile(pm25, 0.95), percent5_10 = quantile(pm10, 0.05), percent25_10 = quantile(pm10, 0.25), percent75_10 = quantile(pm10, 0.75), percent95_10 = quantile(pm10, 0.95))
}



# function to create diurnal plots + save as an svg
diurnal_plot <- function(data, time_str, env_str, pm_str) {
  wknd_labels <- as_labeller(c("TRUE" = "Weekend",
                    "FALSE" = "Weekday"))

  graph_labels <- c("Daily", env_str, pm_str, "Trends", time_str, "Purifier Install", "[ug/m^3]")
  
  data <- filter(data, particle == pm_str)
  
  # # svg file to save graph
  # svg(paste(tolower(time_str), tolower(env_str), pm_str, sep = "_"))
  
  ggplot(data) +
    geom_ribbon(aes(x = time, ymin = percent5, ymax = percent95, fill = "#cfcfcf")) +
    geom_ribbon(aes(x = time, ymin = percent25, ymax = percent75, fill = "#7a7a7a")) +
    geom_line(aes(x = time, y = mean, color = "red")) +
    geom_line(aes(x = time, y = median, color = "blue")) +
    facet_grid(is_wknd ~ ., labeller = wknd_labels) +
    scale_color_identity(name = "Averages",
                            breaks = c("red", "blue"),
                            labels = c("Mean", "Median"),
                            guide = "legend") +
    scale_fill_identity(name = "Percentiles",
                            breaks = c("#cfcfcf", "#7a7a7a"),
                            labels = c("5th - 95th", "25th - 75th"),
                            guide = "legend") +
    scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:00") +
    labs(title = bquote(.(graph_labels[1]) ~ .(graph_labels[2]) ~ PM[.(graph_labels[3])] ~ .(graph_labels[4]) ~ .(graph_labels[5]) ~ .(graph_labels[6])),
         x = "Time of Day (hrs)",
         # Fix y-labelling w/ bquote
         y = expression(paste("PM"[1]*" Concentration (", mu, "g/m"^3*")"))) +
    # scale_y_log10() +
    # scale_y_log10(limits = c(1e-1,1e2)) +
    # ylim(0,75) +
    theme_bw()
  
  # # close the graphics device
  # dev.off() 
}
```
