## Set up
Load libraries, define file paths, include participant IDs to be processed
```{r, warning=FALSE}
# Import relevant libraries
library(ggplot2)
library(pracma)
library(forecastML)
```

Set working directory
```{r, setup, include=FALSE}
knitr::opts_knit$set(root.dir = 'C:/Users/vkuchhal/Documents/hepa-summer23')
```

Check for working directory
```{r}
# Check file path
if (!endsWith(getwd(), "hepa-summer23")) {
  stop("Incorrect working directory")
}
```

```{r}
# Set path to data
path_to_data <- "data/HAFTRAP/OH/cpc/"
# Load CPC data from RData file
load(paste0(path_to_data, "cleaned_cpc.RData"))
```


```{r}
# Filter data to appropriate subset
df <- main_df %>%
  filter(participant_id == "45361", case == "sham", 
         environment == "indoor") %>%
  fill_gaps(frequency = "1 sec") %>%
  mutate(t = as.numeric(date) - as.numeric(date)[1]) %>%
  fill(concent)

```


```{r}
# Function to get the peaks of a dataset
get_peaks <- function(data) {
  findpeaks(data,
                   nups = 1,
                   ndowns = 1,
                   minpeakheight = quantile(data, probs = 0.95)[1],
                   minpeakdistance = 2000,
                   threshold = 0)
}

peaks <- data.frame(get_peaks(df$concent))
colnames(peaks) <- c("vy", "vx", "start", "end") 
```

# Necessary functions to perform decay analysis
```{r}
# Function to get first valley after peak
get_first_valleys <- function(data, peaks, min_threshold) {
  # Iterate through rows of peaks matrix
  valley_mat <- matrix(nrow = nrow(peaks), ncol = 2)
  for (row in 1:nrow(peaks)) { #nolint
    idx <- peaks[row, 2]
    n <- TRUE
    # create while loop to check for local minima
    while (n) {
      # if we're at the end of y, break out of loop
      if (idx == length(data)) {
        n <- FALSE
      } else {
        # otherwise, get slope (approximately)
        # NOTE: difference between idx and (idx+1) is 1
        slope <- data[idx + 1] - data[idx]
        if (data[idx] <= min_threshold && slope > 0) {
          n <- FALSE
          print("Hey!")
        } else {
          idx <- idx + 1
        }
      }
    }
    # set values of matrix so that column 1 is height of valley and 2 is index
    valley_mat[row, 1] <- data[idx]
    valley_mat[row, 2] <- idx
  }
  valley_mat
}

valleys <- data.frame(get_first_valleys(df$concent, peaks, 10000))
colnames(valleys) <- c("vy", "vx") 
```

```{r}
ggplot(df) +
  geom_line(aes(x = t, y = smooth(concent, kind = "3"))) +
  geom_point(data = peaks, mapping = aes(x = vx, y = vy)) +
  geom_point(data = valleys, mapping = aes(x = vx, y = vy)) +
  ggtitle(paste("45361", "sham", "indoor"))
```

```{r}
df %>%
  filter(day(date) == 9) %>%
  filter(hour(date) > 16 & minute(date) > 10) -> section

ggplot(section) +
  geom_line(aes(x = date, y = concent))
  
```

```{r}
time_start <- as.numeric(section$date[1])
section$t <- as.numeric(section$date) - time_start

ggplot(section) +
    geom_line(aes(x = t, y = concent))
```

```{r}
eDecay <- function(t, offs, ampl, tau) (offs + ampl*exp(-t/tau))

model1 <- nls(concent ~ eDecay(t,offs,myA,myT), 
              data=section, start=list(offs=1000,myA=10000,myT=1000))

```

```{r}
section$fit <- predict(model1, newdata = section)
```


```{r}
ggplot(section) +
  geom_line(aes(x = t, y = concent)) +
  geom_line(aes(x = t, y = fit), color = "red")
```

