# HAFTRAP Diurnal Plotting (for CPC)

## STOP

**HAVE YOU RUN `OH_cpc_cleaning`?**
*This file loads a dataframe created from running `OH_cpc_cleaning`. Make sure you run that file first (if you haven't already) before running this file.*

This file is used to create diurnal plots for the HAFTRAP CPC data.

```{r}
# import necessary libraries
library(tidyverse)
library(data.table)
library(scales)
```

```{r, setup, include=FALSE}
# set working directory
knitr::opts_knit$set(root.dir = "~/hepa-summer23")
```

```{r}
# check file path for working directory
if (!endsWith(getwd(), "hepa-summer23")) {
  stop("Incorrect working directory")
}
```

```{r}
# set path to data
path_to_data <- "cleaning/HAFTRAP/OH/"
```

## Load data
```{r}
# Load Mod-PM data from RData file
load(paste0(path_to_data, "cleaned_cpc.RData"))
```

## Main Code Run
```{r}
# Pre-processing to add relevant columns
my_df <- main_df %>%
  # Round date to nearest ten minutes
  mutate(date_round = round_date(date, unit = "10 mins")) %>%
  # Get day of the week as integer from 1 to 7
  mutate(wkdy = wday(date)) %>%
  # Classify as weekday or weekend
  mutate(is_wknd = wkdy %in% c(1, 7)) %>%
  # Extract time of the day from datetime
  mutate(time = as.POSIXct(as.ITime(date_round), format = "%H:%M:%S"))
```

```{r}
# Calculate summary statistics for ever ten minutes
graph_main_df <- my_df %>%
  # For every 10 minutes for given case, environment, weekday/end
  group_by(is_wknd, time, case, environment) %>%
  # Find summary statistics
  summarise(mean = mean(concent),
          median = median(concent), 
          q5 = quantile(concent, probs = 0.05), 
          q25 = quantile(concent, probs = 0.25),
          q75 = quantile(concent, probs = 0.75),
          q95 = quantile(concent, probs = 0.95),
          sd = sd(concent),
          .groups = 'drop')
```

```{r}
# Function to create diurnal plots
diurnal_plot <- function(data, case_str, env_str) {
  # Filter data for specified case, environment
  data %>%
    filter(case == case_str, environment == env_str) %>%
  
  # Make diurnal plot, x-axis as time
  ggplot(aes(x = time)) +
    # Plot the 5th-95th and 25th-75th percentiles
    geom_ribbon(aes(ymin = q5, ymax = q95, fill = "#cfcfcf")) +
    geom_ribbon(aes(ymin = q25, ymax = q75, fill = "#9a9a9a")) +
    
    # Plot the mean and median
    geom_line(aes(y = mean, color = "red")) +
    geom_line(aes(y = median, color = "blue")) +
    
    # Facet based on weekday vs. weekend
    facet_grid(is_wknd ~ ., labeller = 
                 as_labeller(c("TRUE" = "Weekend", "FALSE" = "Weekday"))) +
    
    # Label legend for mean and median
    scale_color_identity(name = "Averages", breaks = c("red", "blue"),
                         labels = c("Mean", "Median"), guide = "legend") +
    
    # Label legend for percentiles
    scale_fill_identity(name = "Percentiles", breaks = c("#cfcfcf", "#9a9a9a"),
                        labels = c("5th - 95th", "25th - 75th"),
                        guide = "legend") +
    
    # Modify x-axis scaling
    scale_x_datetime(date_breaks = "2 hours", date_labels = "%H:00") +
    
    # Label title and axes 
    labs(title = paste("CPC Daily", str_to_title(env_str), "Trends During",
                       str_to_title(case_str),"Period"),
         x = "Time of Day (hrs)",
         y = bquote("UFP Particle Count "(number/m^3))) +
    
    # Set y-axis to log scale
    scale_y_log10(labels = number_format()) +
    
    # Add fun theme
    theme_bw() +
    # Rotate x-axis labels for clarity
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) -> my_plot
  
  # Save plot
  ggsave(filename = paste0("artifacts/HAFTRAP/OH/diurnals/", "OH_cpc_",
                           case_str, "_", env_str, ".png"), plot = my_plot)
  
  # Display plot
  my_plot
}
```

```{r}
# Plot all the diurnal plots
for (case in c("hepa", "sham")) {
  for (env in c("indoor", "outdoor", "ratio")) {
    print(diurnal_plot(graph_main_df, case, env))
    print(paste("Plotted", case, env))
  }
}
```